version: 2.1
orbs:
  docker: circleci/docker@2.6.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          executor:
            image: openweb-app
            name: docker/docker
            tag: boron-browsers
          image: openweb-app
          remote-docker-dlc: true
          tag: my-tag
          use-remote-docker: true
