version: 2.1
orbs:
  docker: circleci/docker@2.6.0
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: orirothschild/openweb-app
      - docker/push:
          digest-path: /tmp/digest.txt
          image: orirothschild/openweb-app
          tag: openweb-app
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push