apiVersion: apps/v1
kind: Deployment
metadata:
  name: openweb-app
  labels:
    app: openweb-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openweb-app
  template:
    metadata:
      labels:
        app: openweb-app
    spec:
      containers:
      - name: openweb-app
        image: orirothschild/openweb-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PASS
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      terminationGracePeriodSeconds: 30
